### ISSUE TITLE
add php installation guide / requirements file

### ISSUE THREAD

**Issue by nnrepos** [michael-maltsev/technion-ug-info-fetcher#1]
@michael-maltsev 
i tried running the fetcher and ran into some issues, it took me a while to realise that this projects depends on `php-curl` and `php-xml` libraries.
i could create an installation guide for ubuntu/windows, or just mention the required libraries.
let me know if you're interested 😀

**Comment by michael-maltsev** [comment]
Hi,
Sure, why not. You can post a short guide as a comment here and I'll link it from the readme.

**Comment by nnrepos** [comment]
i think it would be better to add this to the `README`, but as you wish 😇 
this worked for me on ubuntu:
```bash
# install php, curl, DOM, on ubuntu:
sudo apt update && apt install -y software-properties-common 
sudo add-apt-repository ppa:ondrej/php 
sudo apt update
sudo apt upgrade -y
sudo apt install php8.0 php-curl php-xml php-mbstring -y

# verify version
php -v
```

**Comment by m417z** [comment]
Added a link to your comment to the readme, thanks.

> i think it would be better to add this to the `README`

I haven't tested it, and I'm not going to maintain it, so I prefer to link to your comment to make that clear. It adds an extra click for Linux users, but that's OK. In any case, thanks for the contribution :)

**Comment by michael-maltsev** [comment]
Added a link to your comment to the readme, thanks.

> i think it would be better to add this to the `README`

I haven't tested it, and I'm not going to maintain it, so I prefer to link to your comment to make that clear. It adds an extra click for Linux users, but that's OK. In any case, thanks for the contribution :)
